/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.traale.desktop;

import org.thingml.rtcharts.swing.*;

/**
 *
 * @author ffl
 */
public class HumidityGraphFrame extends javax.swing.JFrame {

    GraphBuffer t1_buffer;
    GraphBuffer t2_buffer;
    GraphBuffer h1_buffer;
    GraphBuffer h2_buffer;
    
    
    /**
     * Creates new form IMUOrientationFrame
     */
    public HumidityGraphFrame(GraphBuffer t1_buffer, GraphBuffer h1_buffer, GraphBuffer t2_buffer, GraphBuffer h2_buffer) {
        this.t1_buffer = t1_buffer;
        this.t2_buffer = t2_buffer;
        this.h1_buffer = h1_buffer;
        this.h2_buffer = h2_buffer;
        
        initComponents();
        ((GraphPanel)jPanelGraphT1).start();
        ((GraphPanel)jPanelGraphT2).start();
        ((GraphPanel)jPanelGraphH1).start();
        ((GraphPanel)jPanelGraphH2).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraphT1 = new LineGraphPanel(t1_buffer, "Temperature 1 (x 0.01°C)", -1000, 5000, 500, new java.awt.Color(0, 204, 51));
        jPanelGraphH1 = new LineGraphPanel(h1_buffer, "Humidity 1 (x 0.01)", 0, 10000, 1000, new java.awt.Color(0, 153, 204));
        jPanelGraphT2 = new LineGraphPanel(t2_buffer, "Temperature 2 (x 0.01°C)", -1000, 5000, 500, new java.awt.Color(0, 204, 51));
        jPanelGraphH2 = new LineGraphPanel(h2_buffer, "Humidity 2 (x 0.01)", 0, 10000, 1000, new java.awt.Color(0, 153, 204));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Temperature and Humidity");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(jPanelGraphT1);
        getContentPane().add(jPanelGraphH1);
        getContentPane().add(jPanelGraphT2);
        getContentPane().add(jPanelGraphH2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ((GraphPanel)jPanelGraphT1).stop();
        ((GraphPanel)jPanelGraphT2).stop();
        ((GraphPanel)jPanelGraphH1).stop();
        ((GraphPanel)jPanelGraphH2).stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelGraphH1;
    private javax.swing.JPanel jPanelGraphH2;
    private javax.swing.JPanel jPanelGraphT1;
    private javax.swing.JPanel jPanelGraphT2;
    private javax.swing.JPanel jPanelGraphTemp4;
    private javax.swing.JPanel jPanelGraphTemp5;
    private javax.swing.JPanel jPanelGraphTemp6;
    // End of variables declaration//GEN-END:variables
}
