/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.traale.desktop;

import java.awt.Color;
import org.thingml.rtcharts.swing.*;

/**
 *
 * @author ffl
 */
public class ThreeAxisGraphFrame extends javax.swing.JFrame {

    GraphBuffer qx_buffer;
    GraphBuffer qy_buffer;
    GraphBuffer qz_buffer;
    String title;
    int min, max, minor;
    Color color;
    
    
    public ThreeAxisGraphFrame(GraphBuffer qx_buffer, GraphBuffer qy_buffer, GraphBuffer qz_buffer, String title, Color color, int min, int max, int minor) {
        this.qx_buffer = qx_buffer;
        this.qy_buffer = qy_buffer;
        this.qz_buffer = qz_buffer;
        this.min = min;
        this.max = max;
        this.minor = minor;
        this.title = title;
        this.color = color;
        
        initComponents();
        
        setTitle(title);
        
        ((GraphPanel)jPanelGraphQY).start();
        ((GraphPanel)jPanelGraphQX).start();
        ((GraphPanel)jPanelGraphQZ).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGraphQX = new LineGraphPanel(qx_buffer, title + " - X", min, max, minor, color);
        jPanelGraphQY = new LineGraphPanel(qy_buffer, title + " - Y", min, max, minor, color);
        jPanelGraphQZ = new LineGraphPanel(qz_buffer, title + " - Z", min, max, minor, color);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));
        getContentPane().add(jPanelGraphQX);
        getContentPane().add(jPanelGraphQY);
        getContentPane().add(jPanelGraphQZ);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ((GraphPanel)jPanelGraphQY).stop();
        ((GraphPanel)jPanelGraphQX).stop();
        ((GraphPanel)jPanelGraphQZ).stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelGraphQX;
    private javax.swing.JPanel jPanelGraphQY;
    private javax.swing.JPanel jPanelGraphQZ;
    // End of variables declaration//GEN-END:variables
}
