/**
 * Copyright (C) 2012 SINTEF <franck.fleurey@sintef.no>
 *
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, Version 3, 29 June 2007;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * 	http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.thingml.traale.desktop;

import java.awt.Color;
import org.thingml.rtcharts.swing.*;

/**
 *
 * @author ffl
 */
public class UpdateRateGraphFrame extends javax.swing.JFrame {

    GraphBuffer t_buffer;
    Color color;
    
    /**
     * Creates new form IMUOrientationFrame
     */
    public UpdateRateGraphFrame(GraphBuffer t_buffer, String title, Color color) {
        this.t_buffer = t_buffer;
        this.color = color;
        initComponents();
        this.setTitle(title);
        ((GraphPanel)jPanelGraphTemp).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ymaxButtons = new javax.swing.ButtonGroup();
        jPanelGraphTemp = new BarGraphPanel(t_buffer, "Update Rate (in ms)", 0, 1000, 100, color);
        jPanel1 = new javax.swing.JPanel();
        jRadioButton250 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton500 = new javax.swing.JRadioButton();
        jRadioButton1000 = new javax.swing.JRadioButton();
        jRadioButton5000 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        ymaxButtons.add(jRadioButton250);
        jRadioButton250.setText("250");
        jRadioButton250.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton250ActionPerformed(evt);
            }
        });

        jLabel1.setText("Y Max (ms) : ");

        ymaxButtons.add(jRadioButton500);
        jRadioButton500.setText("500");
        jRadioButton500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton500ActionPerformed(evt);
            }
        });

        ymaxButtons.add(jRadioButton1000);
        jRadioButton1000.setSelected(true);
        jRadioButton1000.setText("1000");
        jRadioButton1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1000ActionPerformed(evt);
            }
        });

        ymaxButtons.add(jRadioButton5000);
        jRadioButton5000.setText("5000");
        jRadioButton5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5000ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton250)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton500)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1000)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5000))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5000)
                    .addComponent(jRadioButton1000)
                    .addComponent(jRadioButton500)
                    .addComponent(jRadioButton250)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelGraphTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelGraphTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        ((GraphPanel)jPanelGraphTemp).stop();
    }//GEN-LAST:event_formWindowClosed

    private void jRadioButton250ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton250ActionPerformed
        ((GraphPanel)jPanelGraphTemp).setYmax(250);
    }//GEN-LAST:event_jRadioButton250ActionPerformed

    private void jRadioButton500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton500ActionPerformed
        ((GraphPanel)jPanelGraphTemp).setYmax(500);
    }//GEN-LAST:event_jRadioButton500ActionPerformed

    private void jRadioButton1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1000ActionPerformed
        ((GraphPanel)jPanelGraphTemp).setYmax(1000);
    }//GEN-LAST:event_jRadioButton1000ActionPerformed

    private void jRadioButton5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5000ActionPerformed
        ((GraphPanel)jPanelGraphTemp).setYmax(5000);
    }//GEN-LAST:event_jRadioButton5000ActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelGraphTemp;
    private javax.swing.JRadioButton jRadioButton1000;
    private javax.swing.JRadioButton jRadioButton250;
    private javax.swing.JRadioButton jRadioButton500;
    private javax.swing.JRadioButton jRadioButton5000;
    private javax.swing.ButtonGroup ymaxButtons;
    // End of variables declaration//GEN-END:variables
}
